// Mixamo Animations - see ./animations folder
const animations = ['Warming Up.fbx',
  'Surprise Uppercut_3.fbx',
  'Inside Crescent Kick.fbx',
  'Kicking.fbx',
  'Knee Kick Lead.fbx',
  'Armada.fbx',
  'Bencao.fbx',
  'Body Block (1).fbx',
  'Roundhouse Kick_1.fbx',
  'Boxing_1.fbx',
  'Knee Jabs To Uppercut.fbx',
  'Boxing_2.fbx',
  'Roundhouse Kick_2.fbx',
  'Boxing_3.fbx',
  'Surprise Uppercut_1.fbx',
  'Boxing_4.fbx',
  'Surprise Uppercut_2.fbx',
  'Boxing_5.fbx',
  'Martelo Do Chau Sem Mao.fbx',
  'Boxing_6.fbx',
  'Armada To Esquiva.fbx',
  'Boxing_7.fbx',
  'Boxing_8.fbx',
  'Headbutt.fbx',
  'Boxing_9.fbx',
  'Elbow Punch_1.fbx',
  'Boxing_10.fbx',
  'Chapa 2.fbx',
  'Chapa Giratoria 2.fbx',
  'Chapa-Giratoria.fbx',
  'Chapaeu De Couro.fbx',
  'Elbow Punch_2.fbx',
  'Ginga Forward.fbx',
  'Ginga Variation 1.fbx',
  'Knee Jab.fbx',
  'Leg Sweep.fbx',
  'Martelo 2.fbx',
  'Martelo 3.fbx',
  'Martelo Do Chau.fbx',
  'Meia Lua De Compasso.fbx',
  'Outward Block.fbx',
  'Pivot.fbx',
  'Punch To Elbow Combo.fbx',
  'Queshada 1.fbx',
  'Stealth Assassination.fbx',
  'Taunt.fbx'];