// Mixamo Animations - see ./animations folder
const animations = ['Warming Up.fbx',
  'Armada To Esquiva.fbx',
  'Armada_mech.fbx',
  'Armada.fbx',
  'Bencao.fbx',
  'Body Block (1).fbx',
  'Boxing_1.fbx',
  'Boxing_2.fbx',
  'Boxing_3.fbx',
  'Boxing_4.fbx',
  'Boxing_5.fbx',
  'Boxing_6.fbx',
  'Boxing_7.fbx',
  'Boxing_8.fbx',
  'Boxing_9.fbx',
  'Boxing_10.fbx',
  'Chapa 2.fbx',
  'Chapa Giratoria 2.fbx',
  'Chapa-Giratoria.fbx',
  'Chapaeu De Couro.fbx',
  'Elbow Punch_1.fbx',
  'Elbow Punch_2.fbx',
  'Ginga Forward.fbx',
  'Ginga Variation 1.fbx',
  'Headbutt.fbx',
  'Inside Crescent Kick.fbx',
  'Kicking.fbx',
  'Knee Jab.fbx',
  'Knee Jabs To Uppercut.fbx',
  'Knee Kick Lead.fbx',
  'Leg Sweep.fbx',
  'Martelo 2.fbx',
  'Martelo 3.fbx',
  'Martelo Do Chau Sem Mao.fbx',
  'Martelo Do Chau.fbx',
  'Meia Lua De Compasso.fbx',
  'Outward Block.fbx',
  'Pivot.fbx',
  'Punch To Elbow Combo.fbx',
  'Queshada 1.fbx',
  'Roundhouse Kick_1.fbx',
  'Roundhouse Kick_2.fbx',
  'Stealth Assassination.fbx',
  'Surprise Uppercut_1.fbx',
  'Surprise Uppercut_2.fbx',
  'Surprise Uppercut_3.fbx',
  'Taunt.fbx'];